### ISSUE TITLE
✨ Firestore rules

### ISSUE THREAD

**Issue by haavarol** [ecatch-kyst/backend#10]
Firestore needs rules to limit what a user can do. 
This issue extends https://github.com/ecatch-kyst/backend/issues/4

## Expected Behavior

We need several firestore rules to ensure safety for our application. This includes limiting access as well as validating input. These rules should also be tested.

- [x] unauthenticated user should not be able to read or write any data
- [x] authenticated user should only be able to read his own user data
- [x] authenticated user should only be able to read his own messages
- [x] authenticated user should be able to create new messages
- [x] authenticated user should only be able to read his own boat data
- [ ] add tests

## Priority

Fast

## Size

3

**Comment by balazsorban44** [comment]
Apart from testing, this issue has been finished. Postponing tests, closing this issue :lock:
