### ISSUE TITLE
✨ User authentication

### ISSUE THREAD

**Issue by haavarol** [ecatch-kyst/backend#4]
This issue tracks the backend handling of user authentication. 
For the frontend issue see ecatch-kyst/web/issues/10

## Expected Behavior

When a new user is created it should also create a new firestore document with the same uid. When user deletion is requested it should delete the user on uid from firestore.
- [x] add user
- [x] remove user
- [x] add security rules
- [ ] add tests

## Priority

Fast

## Size

4 (implementation, testing, security, frontend)

**Comment by balazsorban44** [comment]
apart from adding tests, is this issue done? @haavarol

**Comment by haavarol** [comment]
Yes, as far as I can tell It is working as intended. I would say it is done @balazsorban44

**Comment by balazsorban44** [comment]
Testing is being postponed. Otherwise finished, closing for now. :lock:
